### PR TITLE
bring back kafka as a dev dependency

### PR DESCRIPTION
**Pull request by alexanderankin**

### CODE REVIEW

**Comment by totallyzen** [comment]
actually, as I understood https://github.com/testcontainers/testcontainers-python/issues/351 we want to actively not make it a dependency because then people can choose between `python-kafka` and `confluent-kafka` for themselves.

I think we can close this and move on with the original PR :pray:

**Comment by gudjonragnar** [comment]
Yes, the dependency is only there initially to implement the waiting logic, as far as i can see.

**Comment by totallyzen** [comment]
I did another round, actually you do need it for running the tests too.

So the simplest thing to do for right now is to add `python-kafka` as a dev dependency.
@alexanderankin added it as an optional dependency too, maybe no need for the latter, just the former.

@gudjonragnar would you please make this change for us on your original PR? Just to make the tests pass. :pray:

**Comment by gudjonragnar** [comment]
I have added it back as a dev dependency on the original PR 👍 . Will close this one.

**Pull request closed without merging**
